#!/bin/bash

# Variable Definitions
userresources="${HOME}"/.Xresources
usermodmap="${HOME}"/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
dotconfig="${XDG_CONFIG_HOME:-${HOME}/.config}"

# MERGE IN DEFAULTS AND KEYMAPS
[[ -f "${sysresources}" ]]  && xrdb -merge "${sysresources}"
[[ -f "${sysmodmap}" ]]     && xmodmap     "${sysmodmap}"
[[ -f "${userresources}" ]] && xrdb -merge "${userresources}"
[[ -f "${usermodmap}" ]]    && xmodmap     "${usermodmap}"

# START SOME NICE PROGRAMS
if [[ -d /etc/X11/xinit/xinitrc.d ]] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        # shellcheck disable=SC1090
        [[ -x "${f}" ]] \
            && source "${f}"
    done
    unset f
fi

# QUERY IF PROGRAM IS ALREADY RUNNING BEFORE EXECUTING.
function run() {
    if ! command pgrep -f "${1}" ;
    then
        "${@}" &
    fi
}

xrandr --output DisplayPort-2 --mode 1920x1080 --rate 165
#xrandr --output LVDS-1 --mode 1366x768 --rate 60
xset s off -dpms
nitrogen --set-zoom-fill --random ~/Pictures/Wallpapers/
run picom --experimental-backends --config "${dotconfig}"/picom/picom.conf -b
run dunst -conf/config "${dotconfig}"/dunst/dunstrc
run flameshot
run volumeicon
run nm-applet
run udiskie --tray
run parcellite
#run cbatticon

# DESKTOP ENVIRONMENT | WINDOW MANAGER
session="${1}"
case "${session}" in
    qtile )
        exec qtile start
        ;;
    * )
        :
        ;;
esac

unset -f run
unset -v session dotconfig
