# shellcheck shell=bash

# Variable Definitions
dotconfig="${XDG_CONFIG_HOME:-${HOME}/.config}"
DE="qtile"  # Desktop Environment

# PATH
export PATH="${PATH}":"${HOME}"/.local/bin

# ENVIRONMENT VARIABLES
export GTK2_RC_FILES="${dotconfig}"/gtk-2.0/gtkrc-2.0
export LESSHISTFILE="${dotconfig}"/less/lesshst
export WGETRC="${dotconfig}"/wget/wgetrc
export QT_STYLE_OVERRIDE=kvantum                   #! Arch linux specific
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority    #! Arch linux specific
# HIST_FILE="${HOME}"/.config/bash/bash_history      #! Windows specific
# [[ ! -f "${HIST_FILE}" ]] && touch "${HIST_FILE}"  #! Windows specific
# export HISTFILE="${HIST_FILE}"                     #! Windows specific

# BASHRC
# shellcheck disable=SC1091
source "${dotconfig}"/bash/bashrc

# XINIT
if [[ "$(tty)" = "/dev/tty1" ]]; then
    pgrep "${DE}" || startx "${dotconfig}"/X11/xinitrc "${DE}"
fi

unset -v DE dotconfig
#unset -v HIST_FILE  #! WINDOWS ONLY
